### ISSUE TITLE
ES6ModuleLoader ctor issue

### ISSUE THREAD

**Issue by mfikes** [swannodette/jsx-fun#1]
In the `jsx-fun` checkout, I tried

```
$ rlwrap lein trampoline run -m clojure.main
Clojure 1.6.0
user=> (require 'jsx-fun.core)
CompilerException java.lang.IllegalArgumentException: No matching ctor found for class com.google.javascript.jscomp.ES6ModuleLoader, compiling:(jsx_fun/core.clj:67:10)
```

I've locally built a `SNAPSHOT` of the Closure compiler, and the `ES6ModuleLoader` ctor in question does indeed exist.

**Comment by swannodette** [comment]
@mfikes and you're sure you built from the commonjs branch?

**Comment by mfikes** [comment]
@swannodette No. I hadn't noticed you forked and patched those ctors. That was it. :) Closing.
